from datetime import datetime

generated = datetime.now().strftime("%Y-%m-%d %H:%M")

from app.exporters.captions import (
    INSTAGRAM_CAPTION,
)

EMAIL_HTML = f"""
<h2>📊 오늘의 부동산 브리핑 | AP Daily</h2>

<p>
오늘 생성된 AP Daily 카드뉴스입니다.
</p>

<hr>

<h3>📱 Instagram Caption</h3>

<pre style="
white-space:pre-wrap;
font-family:Arial,sans-serif;
font-size:15px;
line-height:1.6;
">
{INSTAGRAM_CAPTION}
</pre>

<hr>

<h3>📂 업로드 순서</h3>

<ol>
<li>Cover</li>
<li>Introduction</li>
<li>Issue 1</li>
<li>Issue 2</li>
<li>Issue 3</li>
<li>Issue 4</li>
<li>Issue 5</li>
<li>Today's Insight</li>
<li>Ending</li>
</ol>

<p>
첨부된 PNG를 그대로 업로드하면 됩니다.
</p>

<hr>

<p style="color:#999;font-size:13px;">
Generated by Dustie<br>
{generated}
</p>
"""